sudo: required
os: osx
language: node_js
node_js: "6"
matrix:
  include:
    - osx_image: xcode7.3
      env: DEVICE=9.3

    - osx_image: xcode8.3
      env: DEVICE=9.3
    - osx_image: xcode8.3
      env: DEVICE=10.3

    - osx_image: xcode9.3
      env: DEVICE=10.3
    - osx_image: xcode9.3
      env: DEVICE=11.3

    - osx_image: xcode9.4
      env: DEVICE=11.3
    - osx_image: xcode9.4
      env: DEVICE=11.4
before_script:
  - xcrun simctl list runtimes
  - xcrun simctl list devicetypes
script:
  - npm test && _FORCE_LOGS=1 npm run mocha -- -R spec build/test/**/*-e2e-specs.js
after_success:
  - npm run coverage
