sudo: required
os: osx
osx_image: xcode73
language: node_js
env:
  - DEVICE=9.3
node_js: "6"
install:
  - node --version
  - npm install
  - npm install -g gulp
script:
  - gulp eslint
  - gulp once
  - _FORCE_LOGS=1 gulp e2e-test
after_success:
    - gulp coveralls
